---
title: "Feedback"
output:
  html_document:
    theme: cosmo
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
      number_sections: false
    toc_depth: 4
    css: "styles.css"
---

Trip tables created in the Destination Choice step depend, to some degree, on the travel time between the zones. Feedback loops refers to the process of taking the congested travel time from the traffic assignment step and feeding it back to the trip distribution process. These travel times are iteratively fed back to the trip distribution step to recalculate the trip tables. The purpose of the feedback loop is to include more “realistic” travel times in the distribution, mode choice, and highway assignment steps.  

## Feedback in Destination Choice

# Calculation of Feedback Travel Times 
Feedback travel times are calculated for the highway and transit models to more accurately represent the effect of congestion on the transportation system. 

## Highway travel times and skims
Following highway assignment, new peak highway skims are built using an average of travel times from the assignment and from the previous run. Due to the nature of regional modeling, highway delay can be estimated accurately on an aggregate basis, but can sometimes produce unreasonable results on a link-by-link basis. Since link delay in the model is impacted by the length of the link, queuing onto upstream links (like traffic on a congested ramp spilling back onto a freeway) cannot be accounted for. Highly congested links may also produce unrealistically low speeds (under 1 mph) that cannot occur. To account for this, a minimum speed of 10% of free-flow speed is applied to each link during feedback. 

After the minimum speed is applied, the travel times are averaged with travel times from the previous iteration. An average of the two iterations is used to prevent large oscillations in the travel time, but slows convergence. These travel times are used to create a new set of morning peak highway travel times and impedances, which is used for the next feedback loop. A total of three iterations are used to re-run peak distribution, peak mode choice, and peak assignment. On the third and final pass, the evening peak and off-peak assignments are completed as well. 

## Transit travel times and skims
Initial transit travel times are determined using a look-up table of average bus speeds by facility type and area type. A minimum speed of 90% of the background traffic speed is also calculated and used if it is faster than the lookup speed. Buses typically operate on the same facilities as all other traffic and are impacted by congestion just as much as all other vehicles (except for exclusive guideways, which are unaffected by the feedback process). Therefore, these calculations are repeated and subsequently updated for each feedback iteration. In cases where background traffic is slower in the second iteration than the first, buses should experience a similar effect. Conversely, if background traffic travels faster due to less congestion, buses should benefit as well. This will only occur, however, if the minimum speed (90% of background traffic speed) is lower than the transit lookup speed, since it uses the higher of the two.
