---
title: "MRM25v1.0"
output:
  html_document:
    theme: cosmo
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
      number_sections: false
    toc_depth: 4
    css: "styles.css"
---
The MRM is a regional model. All projects are included where practical and possible. Projects that do not add capacity, are minor intersection improvements, or are small widenings on non-regionally significant roadways may be below the scope of the model and omitted from analysis. All regionally significant projects are included. 

Model projects are referenced by the project index number. A project is selected for a particular model year by index number. Project characteristics (e.g., lanes, facility type, intersection controls) are added to the network before capacities and speeds are estimated. The tables below are grouped by county and sorted by the year the project is to open to traffic. TIP numbers are included where possible.  Some projects cross county and MPO boundaries; these are included at the end of one of the county lists.

The MRM25v1.0 model was prepared for the Rock Hill-Fort Mill Transportation Study (RFATS) 2055 Metropolitan Transportation Plan. As of January 2025, it is currently being reviewed by S.C. Department of Environmental Services (SCDES). The projects represented in the MRM for this model version are described below.

```{r, echo=FALSE, warning=FALSE, message=FALSE}

# Load required libraries
library(readxl)
library(DT)
library(dplyr)

# Define a function to render a datatable
render_datatable <- function(data) {
  datatable(
    data,
    filter = "top",
    options = list(
      pageLength = 20,
      autoWidth = TRUE
    ),
    rownames = FALSE
  )
}

data_project <- read_excel("C:/MRM/docs/other/xlsx/MRM25v1_Projects.xlsx") %>%
  mutate(YEAR = as.character(YEAR)) %>%
  select(YEAR, TIP_NO, PROJECT, CATEGORY, TYPE, COUNTY)

# Render the interactive datatable for project list
render_datatable(data_project)

